
spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 8.137.150.98
      password: 123
server:
  port: 7003

mybatis:
  mapper-locations: classpath*:mapper/*.xml
short-link:
  stats:
    ip: e3a4267533ba7b7457e98b23148b7024
  domain:
    default: 70ash.com

